name: Filter and Test Proxies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours

jobs:
  filter-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests rich pysocks

      - name: Run proxy filter script
        run: |
          python filter_proxies.py

      - name: Commit filtered results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add filtered_proxies.csv
          git commit -m "Update filtered proxies CSV" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
